export default function DevelopersSdksPage() {
  const items = [
    ["JavaScript", "Commercial/DeveloperSDKs/javascript/client.js"],
    ["TypeScript", "Commercial/DeveloperSDKs/typescript/client.ts"],
    ["Python", "Commercial/DeveloperSDKs/python/client.py"],
    ["C#", "Commercial/DeveloperSDKs/csharp/TgmClient.cs"],
    ["PHP", "Commercial/DeveloperSDKs/php/client.php"],
    ["REST examples", "Commercial/DeveloperSDKs/rest-examples.sh"],
    ["Postman", "Commercial/DeveloperSDKs/postman/tgm-api-v1.postman_collection.json"],
  ];
  return (
    <>
      <h1 className="page-title">SDK Downloads</h1>
      <p className="page-sub">Official samples generated by the API platform suite</p>
      <div className="table-wrap">
        <table className="data">
          <thead>
            <tr>
              <th>Language</th>
              <th>Path</th>
            </tr>
          </thead>
          <tbody>
            {items.map(([lang, path]) => (
              <tr key={lang}>
                <td>{lang}</td>
                <td className="mono">{path}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </>
  );
}
