/**
 * Config-driven partner program — change policy here / via store config, not Core.
 */
import type { PartnerProgramConfig } from "./types";

export const DEFAULT_PROGRAM_CONFIG: PartnerProgramConfig = {
  version: 1,
  currency: "USD",
  attribution: {
    cookieDays: 30,
    lastClickWins: true,
    requireVerifiedConversion: true,
    blockSelfReferral: true,
  },
  minPayoutCents: 5000,
  approvalWorkflow: [
    "verified_attribution",
    "commission_created_pending_approval",
    "finance_or_commercial_approve",
    "payout_request",
    "payout_paid",
  ],
  tiers: [
    {
      id: "registered",
      label: "Registered Partner",
      minQualifiedSales: 0,
      minRevenueCents: 0,
      commissionBoostBps: 0,
      description: "Entry tier after approval",
    },
    {
      id: "silver",
      label: "Silver Partner",
      minQualifiedSales: 5,
      minRevenueCents: 50000,
      commissionBoostBps: 100,
      description: "5+ qualified sales or USD 500 attributed revenue",
    },
    {
      id: "gold",
      label: "Gold Partner",
      minQualifiedSales: 20,
      minRevenueCents: 250000,
      commissionBoostBps: 250,
      description: "20+ sales or USD 2,500 attributed revenue",
    },
    {
      id: "platinum",
      label: "Platinum Partner",
      minQualifiedSales: 50,
      minRevenueCents: 1000000,
      commissionBoostBps: 400,
      description: "50+ sales or USD 10,000 attributed revenue",
    },
    {
      id: "enterprise",
      label: "Enterprise Partner",
      minQualifiedSales: 100,
      minRevenueCents: 5000000,
      commissionBoostBps: 600,
      description: "Strategic / high-volume partners",
    },
  ],
  commissionRules: [
    {
      id: "rule_pct_standard",
      label: "Standard percentage (first payment)",
      type: "percentage",
      value: 1500,
      active: true,
      requiresApproval: true,
      notes: "15% of verified first sale payment",
    },
    {
      id: "rule_fixed_trial",
      label: "Fixed bounty on trial activation",
      type: "fixed",
      value: 500,
      planCodes: ["trial"],
      active: true,
      requiresApproval: true,
      notes: "USD 5.00 fixed on verified trial attribution",
    },
    {
      id: "rule_recurring_monthly",
      label: "Recurring residual (monthly)",
      type: "recurring",
      value: 500,
      recurringMonths: 12,
      planCodes: ["monthly"],
      active: true,
      requiresApproval: true,
      notes: "5% residual up to 12 months on verified renewals",
    },
    {
      id: "rule_one_time_lifetime",
      label: "One-time lifetime sale",
      type: "one_time",
      value: 2000,
      planCodes: ["lifetime"],
      active: true,
      requiresApproval: true,
      notes: "20% one-time on lifetime plan",
    },
    {
      id: "rule_bonus_launch",
      label: "Launch bonus campaign",
      type: "bonus",
      value: 1000,
      campaignId: "camp_launch",
      active: false,
      requiresApproval: true,
      notes: "USD 10 bonus when campaign active — enable via config/campaign",
    },
  ],
};
